-- Run this file in Supabase Dashboard > SQL Editor before starting the app.
-- RLS is enabled with no anon/authenticated policies; only the backend's secret-key client accesses these tables.

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  worker_number text not null default '',
  worker_name text not null default '',
  product text not null default '',
  quantity numeric not null default 0 check (quantity >= 0),
  date text not null default '',
  comments text not null default '',
  created timestamptz not null default now()
);

create index if not exists workers_date_id_idx
  on public.workers (date desc, id desc);

create table if not exists public.products (
  name text primary key,
  created timestamptz not null default now()
);

create unique index if not exists products_name_lower_idx
  on public.products (lower(name));

create table if not exists public.daily_summaries (
  date text primary key check (date ~ '^\d{4}-\d{2}-\d{2}$'),
  items jsonb not null default '[]'::jsonb,
  created timestamptz not null default now()
);

alter table public.workers enable row level security;
alter table public.products enable row level security;
alter table public.daily_summaries enable row level security;

insert into public.products (name)
select distinct trim(product)
from public.workers
where trim(product) <> ''
on conflict (name) do nothing;
